# Generated by Django 5.1.4 on 2025-01-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id_post", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.TextField(max_length=140)),
                ("text", models.TextField(max_length=700)),
            ],
        ),
    ]
